# Generated by Django 3.2.3 on 2021-05-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, max_length=800, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=800, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Asignado'), (2, 'Fallido'), (3, 'Completado')])),
                ('asignacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignado', to=settings.AUTH_USER_MODEL)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HitCreadoPor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
